# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vaga", models.CharField(max_length=255)),
                ("requisitos", models.TextField()),
                (
                    "faixa_salarial",
                    models.CharField(
                        choices=[
                            ("até 1000", "Até R$ 1000"),
                            ("de 1000 a 2000", "De R$ 1000 a R$ 2000"),
                            ("de 2000 a 3000", "De R$ 2000 a R$ 3000"),
                            ("acima de 3000", "Acima de R$ 3000"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "escolaridade_minima",
                    models.CharField(
                        choices=[
                            ("ensino_fundamental", "Ensino Fundamental"),
                            ("ensino_medio", "Ensino Médio"),
                            ("tecnologo", "Tecnólogo"),
                            ("ensino_superior", "Ensino Superior"),
                            ("pos_mba_mestrado", "Pós/MBA/Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("pretensao_salarial", models.CharField(max_length=20)),
                ("experiencia", models.TextField()),
                (
                    "ultima_escolaridade",
                    models.CharField(
                        choices=[
                            ("ensino_fundamental", "Ensino Fundamental"),
                            ("ensino_medio", "Ensino Médio"),
                            ("tecnologo", "Tecnólogo"),
                            ("ensino_superior", "Ensino Superior"),
                            ("pos_mba_mestrado", "Pós/MBA/Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidaturas",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vaga", "candidato"), name="unique_vaga_candidato"
                    )
                ],
            },
        ),
    ]
