# Generated by Django 6.0.3 on 2026-04-06 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0002_vaga_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="data_criacao",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2026, 4, 6, 0, 0), null=True
            ),
        ),
    ]
