# Generated by Django 6.0.3 on 2026-04-06 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0003_vaga_data_criacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatura",
            name="data_candidatura",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2026, 4, 6, 0, 0), null=True
            ),
        ),
    ]
