# Generated by Django 6.0.3 on 2026-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
    ]
