# Generated by Django 6.0.3 on 2026-04-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilCandidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("pretensao_salarial", models.CharField(max_length=20)),
                (
                    "ultima_escolaridade",
                    models.CharField(
                        choices=[
                            ("ensino_fundamental", "Ensino Fundamental"),
                            ("ensino_medio", "Ensino Médio"),
                            ("tecnologo", "Tecnólogo"),
                            ("ensino_superior", "Ensino Superior"),
                            ("pos_mba_mestrado", "Pós/MBA/Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
