# Generated by Django 6.0.3 on 2026-04-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_perfilcandidato"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilCandidato",
        ),
    ]
